exports.somaPorDoisController = require('./somaPorDoisController')
exports.somaPrimeiroPeloSegundoController = require('./somaPrimeiroPeloSegundoController')
exports.multiPrimeiroPeloSegundo = require('./multiPrimeiroPeloSegundo')
exports.dividirPrimeiroPeloSegundo = require('./dividirPrimeiroPeloSegundo')
exports.subPrimeiroPeloSegundo = require('./subPrimeiroPeloSegundo')